### ISSUE TITLE
Filebeat Configuration (ELK Stack)

### ISSUE THREAD

**Issue by Crypt0Fox** [ComodoSecurity/openedr#19]
Hi, 

can someone share their Filebeat.yml configuration file? I can't seem to configure it right to show the logs that the OpenEDR collects... it only sends the metadata etc...

My filebeat.yml configuration:

**filebeat.inputs:

- type: log
  enabled: true
  paths:
    - c:\programdata\edrsvc\log\output_events\*
  json.keys_under_root: true
  json.add_error_key: true
  json.message_key: log**

Maybe something to do with multiline.pattern? 

![unnamed (1)](https://user-images.githubusercontent.com/42292967/104889322-b86b8800-5976-11eb-9db7-a9d7b7bbba5f.png)
![unnamed](https://user-images.githubusercontent.com/42292967/104889324-b99cb500-5976-11eb-8aab-b762c7c1ee5f.png)

Thanks ahead!

**Comment by koraycomodo** [comment]
You can use the following multiline configuration:
```yaml
filebeat.inputs:
- type: log
enabled: true
paths:
- C:/ProgramData/edrsvc/log/output_events/*.log
multiline.type: pattern
multiline.pattern: '^{$'
multiline.negate: true
multiline.match: after
processors:
- decode_json_fields:
fields: ["message"]
target: "json"
```
